JWT_SECRET_KEY: 7f186169-ea6d-4bb8-80a1-148329b820c0

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/wanted?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: true
